### ISSUE TITLE
Auto pool not working for local template

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#1219]
Local template always seems to assume it should use an existing pool when submitting  job template.

**Comment by ascobie** [comment]
If there was no pool template, how would we know what kind of pool to create? I guess it assumes that the user has already created a pool.

For example, the user copies a 3ds Max, or Maya job template to customize. They then cannot create any old pool, it needs to be a pool with the correct rendering image and licenses set up. I don't think we can assume enough information to be able to give them an auto-pool form. 

So it doesn't really sound like a bug. More like, by design.

**Comment by timotheeguerin** [comment]
well you can still define auto pool manually in the job template and that should work but batchlabs override the pool info with the picked pool

**Comment by ascobie** [comment]
Ahh yes you can. Good point. Needs more smarts about reading job templates.
