### ISSUE TITLE
Job Statistics: Graph fails to load "Loading Tasks. This can take a long time"

### ISSUE THREAD

**Issue by dazzag24** [Azure/BatchLabs#873]
We are running a batch job with almost 11,000 jobs.  Earlier in the job lifetime the graphs load fine.  However as the number of tasks grows the graphs no longer load.  

We see this message:

"Loading Tasks. This can take a long time"

Furthermore the "download" feature has a nasty habit of downloading an empty CSV which overwrites any previous valid data that you may have already downloaded.

**Comment by timotheeguerin** [comment]
Hi, 

Could you check the logs to see if you have any errors. If you have version 0.9.0 you can click on your profile and there should be a view logs option. Otherwise while on the graph pressing `ctrl+shift+i` should open the console and it should show some errors there hopefully. You can email them to tiguerin@microsoft.com

For the overriding downloading part would you still rather have it download as a different file everytime supposing the previous problem isn't occurring anymore?
